# Generated by Django 5.1.3 on 2024-11-26 16:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_trustee_alter_news_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trustee',
            old_name='avatar',
            new_name='picture',
        ),
        migrations.AddField(
            model_name='trustee',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
