# Generated by Django 5.1.3 on 2024-11-26 17:02

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_avatar_trustee_picture_trustee_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustee',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
