# Generated by Django 5.1.3 on 2024-11-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='publications/covers/')),
                ('file', models.FileField(upload_to='publications/files/')),
                ('date', models.DateField()),
            ],
        ),
    ]
