# Generated by Django 5.1.3 on 2024-11-29 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_partnershipsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipsubmission',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
