# Generated by Django 5.1.3 on 2024-12-05 15:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='events'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='news_images'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='publications/covers'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(upload_to='publications/files'),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='trustee_avatars'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='volunteers'),
        ),
    ]
