# Generated by Django 5.1.3 on 2024-12-10 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_news_content_alter_testimonial_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(blank=True, help_text='The testimonial text.', null=True),
        ),
    ]
