# Generated by Django 5.1.3 on 2024-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_news_content_alter_testimonial_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='partnership_category',
            field=models.CharField(choices=[('Corporate Partnerships', 'Corporate Partnerships'), ('NGO Collaborations', 'NGO Collaborations'), ('Individual Donors and Philanthropists', 'Individual Donors and Philanthropists'), ('Community Engagement', 'Community Engagement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='partnershipsubmission',
            name='partnership_category',
            field=models.CharField(choices=[('Corporate Partnerships', 'Corporate Partnerships'), ('NGO Collaborations', 'NGO Collaborations'), ('Individual Donors and Philanthropists', 'Individual Donors and Philanthropists'), ('Community Engagement', 'Community Engagement')], max_length=50),
        ),
    ]
